version : '3.8'
services:
  server:
    image: linx:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./server
        target: /LinX
